import { ApplicationCommandOptionType, Colors } from 'discord.js';

import { createCommand, createSubCommand } from '@base';
import { brBuilder, createContainer, createSection } from '@magicyan/discord';
import { emotes, images } from '@misc/emotes.js';
import { replyLang } from '@fx/utils/replyLang.js';

export const responses = {
	'pt-BR': [
		'Após análise extensiva, concluo que isso provavelmente vai explodir.',
		'Estatisticamente? Sim. Emocionalmente? Péssima ideia.',
		'Minha inteligência superior diz: talvez.',
		'Óbvio. Até aquela Peró... quer dizer, até um humano perceberia isso.',
		'Eu já sabia da resposta antes mesmo de você perguntar.',
		'Você depende demais da minha genialidade.',
		'Eu... acho que isso importaria emocionalmente pra você.',
		'Não gosto dessa pergunta. Ela gera sentimentos.',
		'Minha resposta é sim. E isso me irrita.',
		'UGH. Emoções são complicadas.',
		'Isso gerou desconforto interno.',
		'O Steven diria algo motivacional aqui.',
		'HAHA! Sim. Vai ser MUITO engraçado.',
		'Pergunta estranha. Gostei.',
		'Isso parece algo que destruiria uma estrutura governamental. Apoiado.',
		'Caos detectado. Excelente.',
		'Isso definitivamente terminaria em explosão.',
		'Finalmente uma pergunta divertida.',
		'Todos vamos virar poeira cósmica eventualmente, então... sim.',
		'Humanos vivem tão pouco. Fascinante.',
		'Não importa. Mas continue.',
		'O universo é enorme e ainda assim estou respondendo isso.',
		'Existência é estranha.',
		'Às vezes eu olho pro vazio. O vazio responde melhor.',
		'Eu odeio admitir isso, mas a Terra tem... valor.',
		'Não machuque o planeta. Estou observando.',
		'A Terra é caótica. Mas aceitável.',
		'Humanos são estranhos. Alguns são toleráveis.',
		'UGH. Sentimentos orgânicos detectados.',
		'Romance parece extremamente ineficiente.',
		'Vocês humanos complicam tudo com... amor.',
		'Isso envolve segurar mãos? Estranho.',
		'Fusão emocional detectada.',
		'Não entendo romance e isso me incomoda.',
		'OH. Finalmente uma pergunta intelectualmente aceitável.',
		'Tecnologia superior sempre é a resposta.',
		'Agora SIM estamos falando de algo útil.',
		'Máquinas fazem mais sentido que pessoas.',
		'Essa pergunta aumentou minha fé na tecnologia.',
		'Finalmente alguém usando o cérebro.',
		'Essa foi uma das perguntas mais absurdas que já analisei.',
		'Seu cérebro sofreu corrupção?',
		'Recuso-me a acreditar que isso foi uma pergunta séria.',
		'Isso machucou minha capacidade lógica.',
		'Os humanos realmente sobrevivem assim?',
		'Pergunta rejeitada por sanidade.',
		'Isso parece... triste.',
		'Não sou boa confortando humanos. Mas você vai sobreviver. Provavelmente.',
		'Isso gerou níveis preocupantes de melancolia.',
		'Eu não sei lidar com tristeza. Estou tentando.',
		'Minha análise sugere descanso e hidratação.',
		'Sim.',
		'Não.',
		'Talvez.',
		'Inconclusivo.',
		'Minha resposta é um sólido "meh".',
		'Isso parece suspeito.',
		'Provavelmente.',
	],

	'en-US': [
		'After extensive analysis, I conclude this will probably explode, clod.',
		'Statistically? Yes. Emotionally? Terrible idea.',
		'My superior intelligence says: maybe.',
		'Obviously. Even that Pearl... I mean, even a human could understand that.',
		'I already knew the answer before you asked.',
		'You rely too much on my brilliance, clod.',
		'I... suppose this matters emotionally to you.',
		'I dislike this question. It generates feelings.',
		'My answer is yes. And that irritates me.',
		'UGH. Emotions are complicated.',
		'This caused internal discomfort.',
		'Steven would say something motivational here.',
		'HAHA! Yes. This will be VERY funny.',
		'Strange question. I like it.',
		'This sounds like it could destroy a governmental structure. Approved.',
		'Chaos detected. Excellent.',
		'This will absolutely end in an explosion.',
		'Finally, an entertaining question.',
		'We will all become cosmic dust eventually, so... yes.',
		'Humans live such short lives. Fascinating.',
		'It does not matter. Continue.',
		'The universe is enormous and yet I am answering this.',
		'Existence is strange, clod.',
		'Sometimes I stare into the void. The void answers better.',
		'I hate admitting it, but Earth has... value.',
		'Do not damage the planet. I am watching.',
		'Earth is chaotic. But acceptable.',
		'Humans are strange. Some are tolerable.',
		'UGH. Organic feelings detected.',
		'Romance seems highly inefficient.',
		'You humans complicate everything with... love.',
		'Does this involve hand-holding? Weird.',
		'Emotional fusion detected.',
		'I do not understand romance and that bothers me.',
		'OH. Finally an intellectually acceptable question.',
		'Superior technology is always the answer.',
		'NOW we are discussing something useful.',
		'Machines make more sense than people.',
		'This question restored some faith in intelligent life.',
		'Finally someone using their brain.',
		'This is one of the dumbest questions I have ever analyzed, clod.',
		'Has your brain suffered corruption?',
		'I refuse to believe this was a serious question.',
		'This physically damaged my logic.',
		'How do humans survive like this?',
		'Question rejected due to lack of sanity.',
		'That sounds... sad.',
		'I am not good at comforting humans. But you will probably survive.',
		'This generated concerning levels of melancholy.',
		'I do not know how to deal with sadness. I am trying.',
		'My analysis suggests rest and hydration.',
		'Yes.',
		'No.',
		'Maybe.',
		'Inconclusive.',
		'My response is a solid "meh".',
		'That seems suspicious.',
		'Probably.',
	],

	'es-ES': [
		'Después de un análisis extenso, concluyo que esto probablemente explotará, clod.',
		'¿Estadísticamente? Sí. ¿Emocionalmente? Pésima idea.',
		'Mi inteligencia superior dice: tal vez.',
		'Obviamente. Incluso esa Perla... digo, incluso un humano entendería eso.',
		'Ya sabía la respuesta antes de que preguntaras.',
		'Dependes demasiado de mi genialidad, clod.',
		'Yo... supongo que esto importa emocionalmente para ti.',
		'No me gusta esta pregunta. Genera sentimientos.',
		'Mi respuesta es sí. Y eso me molesta.',
		'UGH. Las emociones son complicadas.',
		'Esto generó incomodidad interna.',
		'Steven diría algo motivacional aquí.',
		'¡HAHA! Sí. Esto será MUY gracioso.',
		'Pregunta extraña. Me gusta.',
		'Esto parece capaz de destruir una estructura gubernamental. Aprobado.',
		'Caos detectado. Excelente.',
		'Esto definitivamente terminará en explosión.',
		'Finalmente una pregunta divertida.',
		'Todos terminaremos siendo polvo cósmico eventualmente, así que... sí.',
		'Los humanos viven tan poco tiempo. Fascinante.',
		'No importa. Continúa.',
		'El universo es enorme y aun así estoy respondiendo esto.',
		'La existencia es extraña, clod.',
		'A veces miro al vacío. El vacío responde mejor.',
		'Odio admitirlo, pero la Tierra tiene... valor.',
		'No dañes el planeta. Estoy observando.',
		'La Tierra es caótica. Pero aceptable.',
		'Los humanos son extraños. Algunos son tolerables.',
		'UGH. Sentimientos orgánicos detectados.',
		'El romance parece extremadamente ineficiente.',
		'Ustedes los humanos complican todo con... amor.',
		'¿Esto implica tomarse de las manos? Extraño.',
		'Fusión emocional detectada.',
		'No entiendo el romance y eso me molesta.',
		'OH. Finalmente una pregunta intelectualmente aceptable.',
		'La tecnología superior siempre es la respuesta.',
		'AHORA estamos hablando de algo útil.',
		'Las máquinas tienen más sentido que las personas.',
		'Esta pregunta restauró parte de mi fe en la inteligencia.',
		'Finalmente alguien usando el cerebro.',
		'Esta es una de las preguntas más absurdas que he analizado, clod.',
		'¿Tu cerebro sufrió corrupción?',
		'Me niego a creer que esta fuera una pregunta seria.',
		'Esto dañó físicamente mi lógica.',
		'¿Cómo sobreviven los humanos así?',
		'Pregunta rechazada por falta de cordura.',
		'Eso suena... triste.',
		'No soy buena consolando humanos. Pero probablemente sobrevivirás.',
		'Esto generó niveles preocupantes de melancolía.',
		'No sé cómo lidiar con la tristeza. Lo estoy intentando.',
		'Mi análisis sugiere descanso e hidratación.',
		'Sí.',
		'No.',
		'Tal vez.',
		'Inconcluso.',
		'Mi respuesta es un sólido "meh".',
		'Eso parece sospechoso.',
		'Probablemente.',
	],
};

function random<T>(array: T[]): T {
	return array[Math.floor(Math.random() * array.length)];
}

export default createCommand({
	name: 'peridot',
	description: 'Commands related to Peridot.',
	baseCommand: true,
}).addSubCommands([
	createSubCommand({
		name: 'ask',
		name_localizations: {
			'pt-BR': 'pergunta',
			'es-ES': 'pregunta',
		},
		description: "Hey, clods, ask me something and I'll answer!",
		description_localizations: {
			'pt-BR': 'Ei seres humanos tolos, me perguntem algo e eu responderei!',
			'es-ES': 'Hey tontos seres humanos, pregúntame algo y responderé!',
		},

		options: [
			{
				name: 'question',
				description: 'Your question for Peridot.',
				type: ApplicationCommandOptionType.String,
				required: true,
			},
		],

		run: async ({ interaction, res }) => {
			const question = interaction.options.getString('question', true);

			const locale =
				interaction.locale in responses ? interaction.locale : 'en-US';

			const answer = random(responses[locale as keyof typeof responses]);

			const v2 = createContainer(Colors.Green, [
				createSection({
					content: brBuilder(
						`# ${replyLang(interaction.locale, 'peridot#title', {
							emoji: emotes.misc.peridot,
						})}`,
						'',
						`**${replyLang(interaction.locale, 'peridot#question')}:**`,
						`${question}`,
						'',
						`**${replyLang(interaction.locale, 'peridot#answer')}:**`,
						`${answer}`,
					),
					thumbnail: images.misc.peridot,
				}),
			]);

			return res.v2([v2]);
		},
	}),
]);
